services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Enregistrement du listener avec l'injection explicite du EntityManagerInterface
    App\EventListener\UserCreationListener:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    # Autres services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
